import { library } from "@fortawesome/fontawesome-svg-core";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";

import {
  faMugHot,
  faChair,
  faShoppingCart,
  faLeftLong,
  faRightLong,
  faLocationDot,
  faArrowRight,
  faArrowLeft,
  faXmark,
  faTrash,
  faPlus,
  faMinus,
  faChevronRight,
  faSpinner,
  faPenToSquare,
  faCheck,
  faBars,
  faCircleInfo,
  faClock,
  faCouch,
  faEnvelope,
  faGraduationCap,
  faLeaf,
  faMobileScreen,
  faMugSaucer,
  faPeopleGroup,
  faPhone,
  faQrcode,
  faStar,
  faStore,
  faUsers,
  faWifi,
} from "@fortawesome/free-solid-svg-icons";

import { faInstagram, faTiktok, faWhatsapp } from "@fortawesome/free-brands-svg-icons";

library.add(
  faMugHot,
  faChair,
  faShoppingCart,
  faLeftLong,
  faRightLong,
  faLocationDot,
  faArrowRight,
  faArrowLeft,
  faXmark,
  faTrash,
  faPlus,
  faMinus,
  faChevronRight,
  faSpinner,
  faPenToSquare,
  faCheck,
  faBars,
  faCircleInfo,
  faClock,
  faCouch,
  faEnvelope,
  faGraduationCap,
  faLeaf,
  faMobileScreen,
  faMugSaucer,
  faPeopleGroup,
  faPhone,
  faQrcode,
  faStar,
  faStore,
  faUsers,
  faWifi,
  faInstagram,
  faTiktok,
  faWhatsapp,
);

export default FontAwesomeIcon;
